GetData = function(url){
    
    result = read.csv(url)
        
    if('Div' %in% names(result)) names(result)[names(result)=='Div'] = 'LeagueDivision'
    if('Date' %in% names(result)) names(result)[names(result)=='Date'] = 'MatchDate'
    if('HomeTeam' %in% names(result)) names(result)[names(result)=='HomeTeam'] = 'HomeTeam'
    if('AwayTeam' %in% names(result)) names(result)[names(result)=='AwayTeam'] = 'AwayTeam'
    if('FTHG' %in% names(result)) names(result)[names(result)=='FTHG'] = 'FullTimeHomeTeamGoals'
    if('FTAG' %in% names(result)) names(result)[names(result)=='FTAG'] = 'FullTimeAwayTeamGoals'
    if('FTR' %in% names(result)) names(result)[names(result)=='FTR'] = 'FullTimeResult'
    if('HTHG' %in% names(result)) names(result)[names(result)=='HTHG'] = 'HalfTimeHomeTeamGoals'
    if('HTAG' %in% names(result)) names(result)[names(result)=='HTAG'] = 'HalfTimeAwayTeamGoals'
    if('HTR' %in% names(result)) names(result)[names(result)=='HTR'] = 'HalfTimeResult'
    if('Attendance' %in% names(result)) names(result)[names(result)=='Attendance'] = 'CrowdAttendance'
    if('Referee' %in% names(result)) names(result)[names(result)=='Referee'] = 'MatchReferee'
    if('HS' %in% names(result)) names(result)[names(result)=='HS'] = 'HomeTeamShots'
    if('AS' %in% names(result)) names(result)[names(result)=='AS'] = 'AwayTeamShots'
    if('HST' %in% names(result)) names(result)[names(result)=='HST'] = 'HomeTeamShotsOnTarget'
    if('AST' %in% names(result)) names(result)[names(result)=='AST'] = 'AwayTeamShotsOnTarget'
    if('HHW' %in% names(result)) names(result)[names(result)=='HHW'] = 'HomeTeamHitWoodwork'
    if('AHW' %in% names(result)) names(result)[names(result)=='AHW'] = 'AwayTeamHitWoodwork'
    if('HC' %in% names(result)) names(result)[names(result)=='HC'] = 'HomeTeamCorners'
    if('AC' %in% names(result)) names(result)[names(result)=='AC'] = 'AwayTeamCorners'
    if('HF' %in% names(result)) names(result)[names(result)=='HF'] = 'HomeTeamFoulsCommitted'
    if('AF' %in% names(result)) names(result)[names(result)=='AF'] = 'AwayTeamFoulsCommitted'
    if('HO' %in% names(result)) names(result)[names(result)=='HO'] = 'HomeTeamOffsides'
    if('AO' %in% names(result)) names(result)[names(result)=='AO'] = 'AwayTeamOffsides'
    if('HY' %in% names(result)) names(result)[names(result)=='HY'] = 'HomeTeamYellowCards'
    if('AY' %in% names(result)) names(result)[names(result)=='AY'] = 'AwayTeamYellowCards'
    if('HR' %in% names(result)) names(result)[names(result)=='HR'] = 'HomeTeamRedCards'
    if('AR' %in% names(result)) names(result)[names(result)=='AR'] = 'AwayTeamRedCards'
    if('HBP' %in% names(result)) names(result)[names(result)=='HBP'] = 'HomeTeamBookingsPoints'
    if('ABP' %in% names(result)) names(result)[names(result)=='ABP'] = 'AwayTeamBookingsPoints'
    if('B365H' %in% names(result)) names(result)[names(result)=='B365H'] = 'Bet365HomeWinOdds'
    if('B365D' %in% names(result)) names(result)[names(result)=='B365D'] = 'Bet365DrawOdds'
    if('B365A' %in% names(result)) names(result)[names(result)=='B365A'] = 'Bet365AwayWinOdds'
    if('BSH' %in% names(result)) names(result)[names(result)=='BSH'] = 'BlueSquareHomeWinOdds'
    if('BSD' %in% names(result)) names(result)[names(result)=='BSD'] = 'BlueSquareDrawOdds'
    if('BSA' %in% names(result)) names(result)[names(result)=='BSA'] = 'BlueSquareAwayWinOdds'
    if('BWH' %in% names(result)) names(result)[names(result)=='BWH'] = 'Bet&WinHomeWinOdds'
    if('BWD' %in% names(result)) names(result)[names(result)=='BWD'] = 'Bet&WinDrawOdds'
    if('BWA' %in% names(result)) names(result)[names(result)=='BWA'] = 'Bet&WinAwayWinOdds'
    if('GBH' %in% names(result)) names(result)[names(result)=='GBH'] = 'GamebookersHomeWinOdds'
    if('GBD' %in% names(result)) names(result)[names(result)=='GBD'] = 'GamebookersDrawOdds'
    if('GBA' %in% names(result)) names(result)[names(result)=='GBA'] = 'GamebookersAwayWinOdds'
    if('IWH' %in% names(result)) names(result)[names(result)=='IWH'] = 'InterwettenHomeWinOdds'
    if('IWD' %in% names(result)) names(result)[names(result)=='IWD'] = 'InterwettenDrawOdds'
    if('IWA' %in% names(result)) names(result)[names(result)=='IWA'] = 'InterwettenAwayWinOdds'
    if('LBH' %in% names(result)) names(result)[names(result)=='LBH'] = 'LadbrokesHomeWinOdds'
    if('LBD' %in% names(result)) names(result)[names(result)=='LBD'] = 'LadbrokesDrawOdds'
    if('LBA' %in% names(result)) names(result)[names(result)=='LBA'] = 'LadbrokesAwayWinOdds'
    if('PSH' %in% names(result)) names(result)[names(result)=='PSH'] = 'PinnacleHomeWinOdds'
    if('PSD' %in% names(result)) names(result)[names(result)=='PSD'] = 'PinnacleDrawOdds'
    if('PSA' %in% names(result)) names(result)[names(result)=='PSA'] = 'PinnacleAwayWinOdds'
    if('SOH' %in% names(result)) names(result)[names(result)=='SOH'] = 'SportingOddsHomeWinOdds'
    if('SOD' %in% names(result)) names(result)[names(result)=='SOD'] = 'SportingOddsDrawOdds'
    if('SOA' %in% names(result)) names(result)[names(result)=='SOA'] = 'SportingOddsAwayWinOdds'
    if('SBH' %in% names(result)) names(result)[names(result)=='SBH'] = 'SportingbetHomeWinOdds'
    if('SBD' %in% names(result)) names(result)[names(result)=='SBD'] = 'SportingbetDrawOdds'
    if('SBA' %in% names(result)) names(result)[names(result)=='SBA'] = 'SportingbetAwayWinOdds'
    if('SJH' %in% names(result)) names(result)[names(result)=='SJH'] = 'StanJamesHomeWinOdds'
    if('SJD' %in% names(result)) names(result)[names(result)=='SJD'] = 'StanJamesDrawOdds'
    if('SJA' %in% names(result)) names(result)[names(result)=='SJA'] = 'StanJamesAwayWinOdds'
    if('SYH' %in% names(result)) names(result)[names(result)=='SYH'] = 'StanleybetHomeWinOdds'
    if('SYD' %in% names(result)) names(result)[names(result)=='SYD'] = 'StanleybetDrawOdds'
    if('SYA' %in% names(result)) names(result)[names(result)=='SYA'] = 'StanleybetAwayWinOdds'
    if('VCH' %in% names(result)) names(result)[names(result)=='VCH'] = 'VcBetHomeWinOdds'
    if('VCD' %in% names(result)) names(result)[names(result)=='VCD'] = 'VcBetDrawOdds'
    if('VCA' %in% names(result)) names(result)[names(result)=='VCA'] = 'VcBetAwayWinOdds'
    if('WHH' %in% names(result)) names(result)[names(result)=='WHH'] = 'WilliamHillHomeWinOdds'
    if('WHD' %in% names(result)) names(result)[names(result)=='WHD'] = 'WilliamHillDrawOdds'
    if('WHA' %in% names(result)) names(result)[names(result)=='WHA'] = 'WilliamHillAwayWinOdds'
    if('Bb1X2' %in% names(result)) names(result)[names(result)=='Bb1X2'] = 'NumberOfBetbrainBookmakers'
    if('BbMxH' %in% names(result)) names(result)[names(result)=='BbMxH'] = 'BetbrainMaximumHomeWinOdds'
    if('BbAvH' %in% names(result)) names(result)[names(result)=='BbAvH'] = 'BetbrainAverageHomeWinOdds'
    if('BbMxD' %in% names(result)) names(result)[names(result)=='BbMxD'] = 'BetbrainMaximumDrawOdds'
    if('BbAvD' %in% names(result)) names(result)[names(result)=='BbAvD'] = 'BetbrainAverageDrawWinOdds'
    if('BbMxA' %in% names(result)) names(result)[names(result)=='BbMxA'] = 'BetbrainMaximumAwayWinOdds'
    if('BbAvA' %in% names(result)) names(result)[names(result)=='BbAvA'] = 'BetbrainAverageAwayWinOdds'
    if('BbOU' %in% names(result)) names(result)[names(result)=='BbOU'] = 'NumberOfBetbrainBookmakers2.5Goals'
    if('BbMx>2.5' %in% names(result)) names(result)[names(result)=='BbMx>2.5'] = 'BetbrainMaximumOver2.5Goals'
    if('BbAv>2.5' %in% names(result)) names(result)[names(result)=='BbAv>2.5'] = 'BetbrainAverageOver2.5Goals'
    if('BbMx<2.5' %in% names(result)) names(result)[names(result)=='BbMx<2.5'] = 'BetbrainMaximumUnder2.5Goals'
    if('BbAv<2.5' %in% names(result)) names(result)[names(result)=='BbAv<2.5'] = 'BetbrainAverageUnder2.5Goals'
    if('GB>2.5' %in% names(result)) names(result)[names(result)=='GB>2.5'] = 'GamebookersOver2.5Goals'
    if('GB<2.5' %in% names(result)) names(result)[names(result)=='GB<2.5'] = 'GamebookersUnder2.5Goals'
    if('B365>2.5' %in% names(result)) names(result)[names(result)=='B365>2.5'] = 'Bet365Over2.5Goals'
    if('B365<2.5' %in% names(result)) names(result)[names(result)=='B365<2.5'] = 'Bet365Under2.5Goals'
    if('BbAH' %in% names(result)) names(result)[names(result)=='BbAH'] = 'NumberOfBetbrainBookmakersAsian'
    if('BbAHh' %in% names(result)) names(result)[names(result)=='BbAHh'] = 'BetbrainHomeTeamHandicapSize'
    if('BbMxAHH' %in% names(result)) names(result)[names(result)=='BbMxAHH'] = 'BetbrainMaximumAsianHandicapHomeTeamOdds'
    if('BbAvAHH' %in% names(result)) names(result)[names(result)=='BbAvAHH'] = 'BetbrainAverageAsianHandicapHomeTeamOdds'
    if('BbMxAHA' %in% names(result)) names(result)[names(result)=='BbMxAHA'] = 'BetbrainMaximumAsianHandicapAwayTeamOdds'
    if('BbAvAHA' %in% names(result)) names(result)[names(result)=='BbAvAHA'] = 'BetbrainAverageAsianHandicapAwayTeamOdds'
    if('GBAHH' %in% names(result)) names(result)[names(result)=='GBAHH'] = 'GamebookersAsianHandicapHomeTeamOdds'
    if('GBAHA' %in% names(result)) names(result)[names(result)=='GBAHA'] = 'GamebookersAsianHandicapAwayTeamOdds'
    if('GBAH' %in% names(result)) names(result)[names(result)=='GBAH'] = 'GamebookersHomeTeamHandicapSize'
    if('LBAHH' %in% names(result)) names(result)[names(result)=='LBAHH'] = 'LadbrokesAsianHandicapHomeTeamOdds'
    if('LBAHA' %in% names(result)) names(result)[names(result)=='LBAHA'] = 'LadbrokesAsianHandicapAwayTeamOdds'
    if('LBAH' %in% names(result)) names(result)[names(result)=='LBAH'] = 'LadbrokesHomeTeamHandicapSize'
    if('B365AHH' %in% names(result)) names(result)[names(result)=='B365AHH'] = 'Bet365AsianHandicapHomeTeamOdds'
    if('B365AHA' %in% names(result)) names(result)[names(result)=='B365AHA'] = 'Bet365AsianHandicapAwayTeamOdds'
    if('B365AH' %in% names(result)) names(result)[names(result)=='B365AH'] = 'Bet365HomeTeamHandicapSize'
    if('PSCH' %in% names(result)) names(result)[names(result)=='PSCH'] = 'PinnacleClosingHomeWinOdds'
    if('PSCD' %in% names(result)) names(result)[names(result)=='PSCD'] = 'PinnacleClosingDrawOdds'
    if('PSCA' %in% names(result)) names(result)[names(result)=='PSCA'] = 'PinnacleClosingAwayWinOdds'
    
    return(result[c("MatchDate", "HomeTeam", "AwayTeam", "FullTimeHomeTeamGoals", "FullTimeAwayTeamGoals", "FullTimeResult", 
                    "HalfTimeHomeTeamGoals", "HalfTimeAwayTeamGoals", "HalfTimeResult", "MatchReferee", "HomeTeamShots",
                    "AwayTeamShots", "HomeTeamShotsOnTarget", "AwayTeamShotsOnTarget", "HomeTeamFoulsCommitted", 
                    "AwayTeamFoulsCommitted", "HomeTeamCorners", "AwayTeamCorners", "HomeTeamYellowCards",
                    "AwayTeamYellowCards", "HomeTeamRedCards", "AwayTeamRedCards")])
}



